# This workflow will build a Java project with Gradle, create repository tag, and push a new docker image to docker hub
name: Create Tag and Push Image to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
          fetch-depth: 0
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build with Gradle and Push
        run: |
          ./gradlew jib \
          -Djib.to.image=sasanlabs/owasp-vulnerableapp:unreleased \
          -Djib.to.tags=$GITVERSION_SEMVER
